// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using steps_API.Data;

#nullable disable

namespace steps_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230411115053_SeededMovies")]
    partial class SeededMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("steps_API.Model.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFavorite")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Journey to the new Home",
                            ImageUrl = "https://w7.pngwing.com/pngs/871/688/png-transparent-passengers-assassin-s-creed-michael-fassbender-film-blu-ray-disc-chris-pratt-celebrities-film-michael-fassbender-thumbnail.png",
                            Name = "Passengers",
                            Rating = "4.9",
                            isFavorite = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Find a way to live",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfdJURHn9A-EtlfLlRMXu2x-rSd8rsqqgGLaOacH43&s",
                            Name = "Interstellar",
                            Rating = "3.8",
                            isFavorite = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Psycology",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToDLALDCFh1VRbnHmsGHK12L85Acth6b1pSugviiY&s",
                            Name = "Shutter Island",
                            Rating = "3.4",
                            isFavorite = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
